function_body_length:
  - 200 # warning
  - 400 # error

file_length:
  warning: 1000
  error: 1700

identifier_name:
  max_length:
    warning: 70
    error: 100
  excluded:
    - id

large_tuple:
  - 3
  - 4

type_body_length:
  - 300
  - 500

nesting:
  type_level:
    warning: 3
    error: 5

type_name:
  max_length:
    warning: 80
    error: 100

line_length:
  warning: 250
  error: 700
  ignores_comments: true
  ignores_function_declarations: true
  ignores_urls: true
  ignores_interpolated_strings: true

trailing_whitespace:
  ignores_empty_lines: true

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - first_where
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - protocol_property_accessors_order
  - redundant_nil_coalescing
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition

custom_rules:
  no_star_comments:
    name: "No comments of just stars"
    regex: \/\/\s*\*+
    match_kinds:
      - comment
    severity: warning

disabled_rules:
  - notification_center_detachment
  - void_return
  - todo
  - multiple_closures_with_trailing_closure

reporter: "xcode"

